services:
  pyaqueduct_host:
    build:
      context: ../..
      dockerfile: containers/integration_tests/Dockerfile
    # image: python:3.10-slim-buster
    # user: dev_user

    depends_on:
      - aqueductcore

    container_name: pyaqueduct-host-dev
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    volumes:
      # Use a named volume for the source code
      - ../..:/workspace

  aqueductcore:
    image: aqueducthub/aqueductcore-dev:latest
    container_name: aqueductcore-server
    depends_on:
      postgres:
        condition: service_healthy

    environment:
      EXPERIMENTS_DIR_PATH: /tmp/aqueduct_experiments
      EXTENSIONS_DIR_PATH: /tmp/aqueduct_extensions
      POSTGRES_USERNAME: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: aqueduct

    volumes:
      - /tmp/aqueduct_experiments:/tmp/aqueduct_experiments
      - /tmp/aqueduct_extensions:/tmp/aqueduct_extensions

    ports:
      - "8000:8000"

  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d aqueduct"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=aqueduct
    expose:
      - 5432
